set timeout 10

trap {
		if [catch {wait -i -1} output] return
		if {[lindex $output [expr [llength $output] -1]] != 0 } {
		exit [lindex $output [expr [llength $output] -1]]
	}
} SIGCHLD

spawn -noecho /opt/ericsson/nms_bismrs_mc/bin/configure_smrs.sh delete nedss

for {} 1 {} {
	expect {
		eof break
		"Please enter number of required option:" { send "1\r" }
		"Are you sure you want to delete this NEDSS 192.168.0.8*" { send "yes\r"}
		timeout { exit 1 }
			}		
}

