set VERSANT_BIN /ericsson/versant/bin
spawn  su - nmsadm -c $VERSANT_BIN/vrsnt_admin.sh
expect "Enter your choice:"
send "1\r"
expect "Press <Return> to continue:"
send "\r"
expect {
   "Enter your choice:" {
   send "0\r"
   exp_continue
  }
  "Do you want to start the offline database before you leave?(y or n)" {
  send "n\r"
  exp_continue
  }
 "Do you want to set all unstartable databases into multi-user mode before you leave?(y or n)" {
  send "n\r"
 }
}

