set timeout 10

trap {
	if [catch {wait -i -1} output] return
	if {[lindex $output [expr [llength $output] -1]] != 0 } {
	exit [lindex $output [expr [llength $output] -1]]
}
} SIGCHLD

spawn -noecho /opt/ericsson/nms_bismrs_mc/bin/configure_smrs.sh delete smrs_master

for {} 1 {} {
	expect {
		eof break
		"ERROR configure_smrs.sh: Unable to determine SMRS master server IP." { exit 0 }
		timeout { exit 1 }
	}
}
