set timeout 40

trap {
	if [catch {wait -i -1} output] return
	if {[lindex $output [expr [llength $output] -1]] != 0 } {
		exit [lindex $output [expr [llength $output] -1]]
	}
} SIGCHLD

spawn -noecho sftp smo-keystore-oss1@smrs_master

expect {
	"Password" {
	} default {
		exit 1
	}
}
sleep 0.15
send -- "shroot12\r"
expect {
	"sftp>" {
	} default {
		exit 2
	}
}
sleep 0.15
send -- "bye\r"

set timeout 300
expect {
    EOF {}
    timeout { exit 99 }
}
sleep 2
